version: "3"

services:

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./theme:/opt/jboss/keycloak/themes/ecocloud
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"